const DOTS_COUNT = 2;
const PAGE_RANGE_DISPLAYED_FROM_SIDES = 3;
export const DOTS = "...";
export const FIRST_PAGE_INDEX = 1;
export const ADJACENT_COUNT = 2;
export const SECOND_ITEM_FROM_SIDES = 2;
export const TOTAL_NUMBER_OF_INITIAL_PAGES =
  ADJACENT_COUNT + PAGE_RANGE_DISPLAYED_FROM_SIDES + DOTS_COUNT;
export const TOTAL_PAGE_COUNT_DISPLAYED =
  PAGE_RANGE_DISPLAYED_FROM_SIDES + ADJACENT_COUNT;
